name: Deploy to test-env
on:
    push:
        branches: [master]

 

jobs:
    prod-env:
        runs-on: ubuntu-latest

 

        steps:
        - name: Deploying in "test-env"
          uses: appleboy/ssh-action@master
          with:
            host: 3.108.215.167
            username: root
            key: ${{ secrets.EC2_SSH_KEY }}
            port: 22
            script: |                 
                cd 
                /root/nodejs-on-ec2
                git pull origin master
                npm install
                npm run build
                pm2 restart 0
                exit
